Add rule for `com.intellij:annotations` and `org.jetbrains:annotations`
gradlex-org/java-ecosystem-capabilities pull request #42
Opened 2023-02-10 15:13 UTC by boris-petrov

Fixes #39 

cc @jjohannes 

I've no idea if what I did is correct, I'm not sure how to test it. :D You might add some info on building to the README. I also am not sure how to generate the `build.out` file for the two sample projects?

2023-02-15 20:04 UTC, jjohannes commented
Thanks @boris-petrov.

Yes I should provide better instructions for contributing (#13 ... too much to do...)

For the tests, you can look at the test report and it will show the changed output. You can then copy/paste that into `build.out` (and double check if it is what you would expect).

The README will update automatically when running `check`.

2023-02-15 20:56 UTC, boris-petrov commented
@jjohannes thanks for the help! I believe everything is fine now. But please double-check. :)

2023-02-15 21:20 UTC, jjohannes requested changes

2023-02-15 21:20 UTC, jjohannes commented on src/main/java/org/gradlex/javaecosystem/capabilities/rules/IntellijAnnotationsRile.java
> +public abstract class IntellijAnnotationsRile implements ComponentMetadataRule {
```suggestion
public abstract class IntellijAnnotationsRule implements ComponentMetadataRule {
```

small typo

2023-02-16 07:34 UTC, boris-petrov commented
Nice catch! Force-pushed.

2023-02-16 07:39 UTC, jjohannes approved these changes

2023-02-16 13:34 UTC, merged